### ISSUE TITLE
Remember max_age will fail in Internet Explorer with default session factory

### ISSUE THREAD

**Issue by mlindemu** [Pylons/pyramid#1243]
Just spent the last couple of days debugging this one.  I could authenticate users through Facebook on both Firefox and Chrome, but Internet Explorer failed every time.  Internet Explorer would receive the Set-Cookie for auth_tkt cookies, but would not keep them beyond the one response.

The problem is that Internet Explorer does not handle the max-age Set-Cookie parameter correctly.  It uses the seconds in the max-age field to replace the expires field which expects a format of  Wdy, DD Mon YYYY HH:MM:SS GMT (from RFC 1123 http://tools.ietf.org/html/rfc1123).

For example, this remember statement will not set a cookie in IE beyond the initial response:
headers = remember(self.request, user.id, max_age=86400)

Django had this same issue.  See: https://code.djangoproject.com/ticket/13548

I'm not sure what they did, but I suspect they probably set the Expires cookie field with an RFC1123 string set max-age seconds in the future from the time that the cookie is generated.

**Comment by olemoign** [comment]
An update on this, as I just encountered the situation.

The problem is linked to the pyramid documentation which shows that the 'max_age' parameter of 'remember' should be a string ( http://docs.pylonsproject.org/projects/pyramid//en/latest/api/security.html ). If you use a string, webob just copies the max_age to the 'Expires' attribute of the cookie, which seems to be ok with other browsers but fails on IE (the cookie isn't set).
If you use an int, everything's fine.

**Comment by mcdonc** [comment]
@olemoign to be sure this is related to the OP's issue, you're using the AuthTktAuthenticationPolicy, right?

**Comment by olemoign** [comment]
@mcdonc Yes.

**Comment by bertjwregeer** [comment]
This may be something I need to fix in WebOb. The `max_age` should be an integer because it defines for how long the cookie should be valid (in seconds). The expires part of a cookie can be calculated from the max age, and that is what is done if the max age is set to an integer. WebOb doesn't expose a way to set the expires header manually, so verifying that `max_age` is an string that can be converted to an `int` will definitely help.

That being said, IE throwing the cookie away entirely when failing to parse an attribute is entirely invalid according to RFC6265.

**Comment by bertjwregeer** [comment]
WebOb now verifies that `max_age` is an integer, and will raise a `ValueError` if it isn't.

**Comment by bertjwregeer** [comment]
(Starting in 1.5.x)
