### ISSUE TITLE
request.route_url handling of "remainder match"

### ISSUE THREAD

**Issue by tisdall** [Pylons/pyramid#1366]
In http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/urldispatch.html#route-pattern-syntax it gives an example of a route as `foo/{baz}/{bar}*fizzle`.  This works fine when matching URLs shown in the examples.  However, there doesn't appear to be any way to generate those URLs using route_url without changing the pattern into `foo/{baz}/{bar}/*fizzle`.

Using pattern `foo/{baz}/{bar}*fizzle`, `request.route_url('foobar', baz=1, bar=2, fizzle=(4, 5))` will not give "http://example.com/foo/1/2/4/5" as hoped, but instead gives "http://example.com/foo/1/24/5".

I understand the reasons behind this, but it seems that the results from matchdict should be able to be put back into route_url and you end up with the original URL.

**Comment by rach** [comment]
I had the similar problem and I ended doing 
    
        request.route_url('foobar', baz=1, bar=2, fizzle='/%s/%s' % (4, 5))

Is it possible to detect if the previous character ended with a slash or not?

**Comment by mmerickel** [comment]
It's not possible to do generically but a pregenerator could prefix the `/` onto the element and perform the job you're describing on a route-by-route basis. I think this is the best way to make it easy to generate urls for these routes. Like I said the only generic solution I can think of is if `*foo` was redefined was being only on url segment boundaries which is unlikely to happen due to compatibility reasons.
