### ISSUE TITLE
render_to_response should not affect request.response

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#1536]
Related to #1534 and #1111 (3803d92fc0da5282656d4229e063a1908ec5522a).

I think that `render_to_response` should use a new response object acquired from the `IResponseFactory`. This should be possible in the same way as #1111 where a new response is created/returned and then `request.response` is restored to its pervious value.

In reality the renderer api should accept an optional `response` object that they can mutate instead of having them mutate `request.response` but this is where we are.

**Comment by jvanasco** [comment]
+1 for this idea.

The reservation I have is that the docs currently show (via the pseudo-official cookbook) that a developer should be expecting/mutating the request.response when defining custom renderers.  When compared with the official shipped renderers, I can't think of a reason why a developer would think otherwise -- so I think this would probably break any existing custom renderers and should be integrated with caution.    I definitely think this approach should be integrated though.

* http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/templates/customrenderers.html

**Comment by mmerickel** [comment]
I think you'll find that it won't break anything if you look at the implementation in https://github.com/Pylons/pyramid/commit/3803d92fc0da5282656d4229e063a1908ec5522a.

Specifically the only thing that would break is people who expect `render_to_response` to return the same thing as `request.response` which I'm claiming is silly.

`request.response` is an object that is used by automated renderers when returning a dict from a view, and I wouldn't (don't) expect it to be used when calling `render_to_response`.

**Comment by jvanasco** [comment]
I agree it's silly, but I think the docs and sample code teach people otherwise.

That being said, I'm enthusiastically for this behavior change -- I just wanted to note up a potential incompatibility.  So I'm just going to agree with you blindly !
