### ISSUE TITLE
Issue with submodules in ssh behind a proxy.

### ISSUE THREAD

**Issue by sbrunner** [Pylons/pyramid#1596]
Hello,

We use the development version as it:
pip install -e git+https://github.com/Pylons/pyramid@af810c54fa9829096085f0ca601030c4fb74b5c7#egg=pyramid
But it don't works when we are behind a proxy.

Than I create this fork to use the submodule in https.
https://github.com/sbrunner/pyramid/tree/c2cgeoportal

Is it possible to backport it ?

**Comment by mmerickel** [comment]
> Is it possible to backport it ?

I don't understand what you're asking us to do.

**Comment by mmerickel** [comment]
Oh, your branch changed the submodule to https. Why don't you package the development version into a zip or wheel instead of using a source checkout? Then you wouldn't need to worry about any of this?

**Comment by sbrunner** [comment]
Effectively we can do that, event if we prefer to get it directly from the official source...

**Comment by mmerickel** [comment]
We have a history of being fairly unsympathetic to people who aren't using officially distributed versions from PyPI. I think instead of fixing the tree to work with your needs You'd get a lot more mileage out of setting up an internal devpi server and putting a local copy of pyramid on it with any fixes you like. The new [PEP440 version numbers](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) allow for a `1.6+local0` concept where you can provide a local version number.

**Comment by mmerickel** [comment]
related to #1614

**Comment by stevepiercy** [comment]
Closing through multiple PRs as noted above.

**Comment by sbrunner** [comment]
Many thanks :-)
