### ISSUE TITLE
Implicit tween ordering produces strange result

### ISSUE THREAD

**Issue by fubu** [Pylons/pyramid#1616]
Pseudocode:

```python
from pyramid import config, tweens
conf = config.Configurator()

conf.add_tween("some.tween_a", under=tweens.EXCVIEW)
conf.add_tween("some.tween_b", over=tweens.MAIN)
conf.add_tween("some.tween_c", over=tweens.EXCVIEW)
```

With the above, I would expect `ptweens` to output the following:

```
Position    Name
--------    ----
-           INGRESS
0           some.tween_c
1           pyramid.tweens.excview_tween_factory
2           some.tween_a
3           some.tween_b
-           MAIN
```

Instead, the output I get with Pyramid 1.5.2 (note that `tween_b` is placed right under `INGRESS` instead of right above `MAIN`):

```
Position    Name
--------    ----
-           INGRESS
0           some.tween_b
1           some.tween_c
2           pyramid.tweens.excview_tween_factory
3           some.tween_a
-           MAIN
```

If I remove adding `tween_c` the implicit ordering is as expected:

```
Position    Name
--------    ----
-           INGRESS
0           pyramid.tweens.excview_tween_factory
1           some.tween_a
2           some.tween_b
-           MAIN
```

Is this the expected behaviour (meaning I better use explicit tween ordering)?

**Comment by mmerickel** [comment]
The implicit ordering is a topological sort. If you do not properly constrain where the tween should appear then you see what you are seeing. For example, you only said it should appear over `MAIN` but not under anything. So as you can see, **it is** over `MAIN`.  In general over `MAIN` is redundant/implied and you just need to specify under `EXCVIEW`.

**Comment by fubu** [comment]
But why is it doing the "right thing" when I only add tweens A and B, but as soon as C is added the order is "messed up"? What change in the ordering algorithm does adding C trigger?

Also, adding `under=tweens.EXCVIEW`moves tween B between EXCVIEW and tween A, which is not exactly what I was aiming for. :)
Is there a way to achieve the expected sorting (first `ptweens` output) with implicit ordering?

**Comment by mmerickel** [comment]
Again, the tweens are generating a directed acyclic graph and then using a topological sort on it to come up with a dependency-based ordering. If you know what I'm talking about it will be clear why the order is not automatically deciphered from what you are specifying. Many times there is more than one possible ordering. It is ambiguous and you are seeing one of the possible solutions.

You can use explicit ordering or just provide more constraints.

```python
conf.add_tween("some.tween_a", under=tweens.EXCVIEW, over='some.tween_b')
conf.add_tween("some.tween_b") # note that a is under excview and over b so b will be automatically under excview
conf.add_tween("some.tween_c", over=tweens.EXCVIEW)
```

We could potentially consider something like `over=MAIN` to imply `under=EXCVIEW`, and `under=INGRESS` to imply `over=EXCVIEW` because otherwise caring about main and ingress really has no effect. However we try to keep things completely under your control and that extra side-effect may be weird to some people.

**Comment by fubu** [comment]
Okay, that makes a lot more sense now (never really thought about the complexity of the implicit ordering problem ;)). I'll use some more constraints then, thanks! :)
