### ISSUE TITLE
CSS and cache busting

### ISSUE THREAD

**Issue by miohtama** [Pylons/pyramid#1654]
Pyramid 1.6 has gained nice cache busting support:

http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/assets.html?highlight=cachebust#cache-busting

I assume many Pyramid developers will face this issue: when cache busting is enabled, what would be the correct way to refer cache busted assets in CSS files? The CSS itself is nicely cache busted, but if you want to refer a cache busted image inside the CSS itself, like the background image of the site, things might get somewhat complex.

A simple solution is only to use relative URLs in CSS `url()`

    body {
        background: url(../img/background.jpg) no-repeat fixed;
    }

... instead of...

    body {
        background: url(/static/theme/img/background.jpg) no-repeat fixed;
    }

This would come out as:

    https://site/static/1eeb262c7175a1f2ea54b459205fc29e/theme/img/background.jpg

... and in the case to update the background image, one needs to bump the CSS file to make sure new cache bust URL gets generated for the CSS file.

Are there other solutions and community best practices? I'd imagine somebody writes / must have written a view which servers CSS files with cache busting URL rewrite.

I'd like to document this solution and potential other solutions, out as I myself stumbled upon this issue and feel many others might ponder this too and it is not being addresses in the cache busting documentation clearly.

**Comment by stevepiercy** [comment]
@miohtama I encourage you to write up your findings, include them in the Pyramid docs, and submit them as a PR to the '1.6-branch' or 'master' branch of Pyramid. The relative URL pattern is definitely worth mentioning.

However, developers may use [JavaScript or CSS compilers](http://webassets.readthedocs.org/en/latest/builtin_filters.html#filters-css-compilers) that already handle this specific issue. The implementation details are beyond the scope of Pyramid documentation, yet a link to those resources would be appropriate.

**Comment by miohtama** [comment]
Thanks @stevepiercy!  I am compiling CSS from LESS source myself. However it is a bit beyond my understanding how I could include cache busted references in LESS, as the the default Pyramid set up does the cache busted URLs on run-time. I would need to provide my own cache buster mechanism of some kind and also have LESS support for it? If somebody knows something about these I'd hope to receive a pointer to right direction.

**Comment by blaflamme** [comment]
@miohtama my frontend workflow is independent from pyramid itself. You can use Grunt, Gulp, Webpack or any tools you feel comfortable with. With a good workflow you should somehow export a manifest file that specify your hash and/or your assets, then you can read this file at startup, from pyramid, and make the right references.

**Comment by miohtama** [comment]
Yes, I am still trying to figure out the good workflow part as this is quite complex issue. If anyone still has experience can you please clarify this 

* I have a `theme` and `theme/img` folder under my `static` folder

* My LESS/CSS files make references to `img/image.jpg`. Also my Pyramid templates make `request.static_url()` references to `img/image.jpg`

* `request.static_url()` references go throught cache buster and are MD5 prefixed to `1eeb262c7175a1f2ea54b459205fc29e/theme/img/background.jpg` when HTML is being generated

* However this does not happen for LESS/CSS and this is my question. Should I in-process / post-process to my CSS/LESS to have the same MD5 path hashing scheme in url() or is there some other cache busting extension way I need to incorporate to my CSS postprocessing?

For *with a good workflow you should somehow export a manifest file that specify your hash and/or your assets, then you can read this file at startup, from pyramid, and make the right references.* I have no idea how to look, where to look, what to read, where to put it and what make all out of this.

Any pointer to any working cache busting example, with CSS considered, would be a good starting point.

**Comment by stevepiercy** [comment]
@miohtama I suggest asking in #pyramid on irc.freenode.net or the [Pylons-Discuss](https://groups.google.com/forum/#!forum/pylons-discuss) mailing list for a "best practice" workflow to compile static assets. Also consult your tool's documentation or community, Stack Overflow, and a search engine. It's outside the scope of Pyramid.

To expand on @blaflamme's comment, an overview of the process is the following.

1. Write LESS/SCSS/SASS/etc. files.
2. Define a function using your tool's features that writes to a manifest file which specifies your hash/path/static files to include in your project (and which Pyramid will read on startup of your web app).
3. Compile your static files.
4. Configure Pyramid to read the manifest at startup.

Your relative URL finding is still a good topic to include in the Pyramid docs. Please do submit a PR for that at least.

**Comment by miohtama** [comment]
Thanks @stevepiercy  - I'll submit pull request first for the relative path trick and then expand the scope of the documentation for pointers for more heavy handed solutions after consulting mailing list / IRC.

**Comment by mmerickel** [comment]
Well unfortunately this got merged before I had a chance to review it. I've been pretty heavy into pyramid + cache busting and I can say that there are only a few options.

- Use an external asset pipeline and a custom cache buster + manifest to synchronize the css urls with those generated within pyramid.

- Use a tween/middleware to postprocess css/js files and inject the correct urls based on their md5 values (you could probably also do this in a custom cache buster).

The proposed solutions in #1655 are really not viable solutions for any real app. The first option (relative urls) still requires bumping the css file manually every time the image changes since the image url is now dependent on the css url (and that's assuming you're using path-based cache busting). The second option is removing all urls from css and placing them in javascript which is obviously unmaintainable.

**Comment by stevepiercy** [comment]
@mmerickel I'd like to incorporate your two options in the docs. Can you produce examples of how to implement them?

I also picture a summary table of technique name, advantages, disadvantages, and use case, at the top of the section, to serve as an implementation guide.

It might be better as a Cookbook recipe, too.

**Comment by miohtama** [comment]
@mmerickel Great! 

The only benefit of solutions presented here are is that they work with vanilla Pyramid. It explains the problem and some half way there ways to mitigate it which work on small sites and teams. Also the second example is not putting any URLs to JavaScript, but how to pass static URLs to JavaScript in the first place if JavaScript needs to access them.

The problem with proper cache busting solution is that it is out of the scope of Pyramid project, as discussed here earlier. Thus, finding good third party examples how to do cache busting is a must.

**Comment by mmerickel** [comment]
@miohtama I definitely agree. I read the new docs as suggesting a different way to change the background image using javascript when obviously it should be done in css just because the examples are so similar.

Nonetheless Pyramid's docs itself should advocate "correct" solutions and the instructions we've merged belong more as a cookbook recipe than in the core docs since these solutions quite simply do not work in a general way.

I think this is somewhat easily solved in Pyramid with a custom cache buster + tween, but requires someone to do that work. I can envision a tween that intercepts any `text/css` responses and parses them, finds urls, and then uses `request.static_url` to fill in a new url. This would work in every case but it could be slow and not be recommended for production. Without this tween, you simply cannot use the new cache busting features without doing something yourself.

Perhaps something like pyramid_webassets could be extended with this type of support but I'm not sure.

In the short term we should definitely update the docs to talk about the options that will work generally such as an example cache buster that parses and uses a manifest.

**Comment by stevepiercy** [comment]
@mmerickel also for the short-term, should I pull the additions by @miohtama from the Pyramid docs into the Cookbook?

**Comment by stevepiercy** [comment]
FYI, I'll be submitting a PR for ``narr/assets.rst`` today as part of my consistency cleanup of narrative docs from 1.5-branch and later.

**Comment by mmerickel** [comment]
This issue should be closed/satisfied whenever #2013 is complete.
