### ISSUE TITLE
add_view api docs describe decorator incorrectly

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid#1726]
The api docs for [add_view](http://pyramid.readthedocs.org/en/1.5-branch/api/config.html#pyramid.config.Configurator.add_view) claim that using the decorator arg is equivalent to using the decorator on the view callable directly. However, according to the diagram at the [router docs](http://pyramid.readthedocs.org/en/1.5-branch/narr/router.html), the decorator arg wraps the function outside of the view mapper, rather than inside. This is misleading.

**Comment by mmerickel** [comment]
I don't see anywhere in the docs that say it is equivalent. They say "It is similar... except with the benefits of a standard call syntax".

It could be more clear what this means but it should be obvious that it's not equivalent because it doesn't have the same signature, so assuming the same return type is also incorrect.

We should probably just update the paragraph to explain that the return of the wrapped view is always a response object. If you want to do that I'll be happy to merge it.

**Comment by mmerickel** [comment]
I think I've improved the docs enough to close this in 6e0f02a.

**Comment by inklesspen** [comment]
looks good to me
