### ISSUE TITLE
Documentation CSS is broken

### ISSUE THREAD

**Issue by Natim** [Pylons/pyramid#1808]
![fx_gliches](https://cloud.githubusercontent.com/assets/229453/7857482/eaf6855e-0530-11e5-887b-7c43dfca336a.png)

Same result with both Firefox 38.0 and Chrome 43.0 on Linux

On this page: http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/api/security.html#pyramid.security.principals_allowed_by_permission

**Comment by stevepiercy** [comment]
@Natim the 1.0-branch (and up through the 1.4 branch) of Pyramid is no longer supported, as implied by the friendly red button in the lower right, "Read the latest version of this page". I stopped backporting updates to the theme with the 1.3-branch. You are more than welcome to submit a PR that updates the theme in accordance with the latest branch (now at v.1.5.7). Otherwise, please close this issue. Thank you!

**Comment by Natim** [comment]
OK sorry you are right I wasn't reading the right version. Please close.
