### ISSUE TITLE
ACL "deny" rules should always supersede "allow"

### ISSUE THREAD

**Issue by jstoiko** [Pylons/pyramid#1856]
The [security chapter of the documentation](http://pyramid.readthedocs.org/en/stable/narr/security.html#elements-of-an-acl) states that *"Each ACE in an ACL is processed by an authorization policy in the order dictated by the ACL"*, it also gives two examples of the same set of entries in opposite order explaining how the former allows while the latter denies. However, I believe that "deny" should always supersede "allow" no matter in which order "deny" is provided.

Note: this issue was uncovered while trying to store ACLs in database records. In order to filter collections of records according to current user's permission, db queries have to be: get all records that "allow" me AND don't "deny" me. Db queries will return the same records even if the "allow" rule is before the "deny" rule.

**Comment by pauleveritt** [comment]
@jstoiko I also recently was working on database filtering via ACLs. If you're interested, drop me a note, paul at agendaless dot com.

**Comment by mmerickel** [comment]
You're free to implement your own `ACLAuthorizationPolicy` that does exactly what you're saying but I think the current one has some distinct performance advantages in its top-down approach and allows for very fine-grained logic between ACLs. In general I think you're probably right that people almost always expect DENY to come before ALLOW in the ordering but as we don't define the meaning of each principal it's hard to know.

**Comment by mcdonc** [comment]
Apologies, but this won't change.  An ACL is ordered.  That's the definition of an ACL as opposed to some other sort of security concept.

**Comment by jstoiko** [comment]
I researched how other systems were dealing with this and I felt like sharing.
- OS X [places deny rules first](https://discussions.apple.com/thread/130477?start=0&tstart=0): *"Deny rules will always have lower numbers than allow rules, so every deny rule is evaluated first"*
- Windose [also](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379298(v=vs.85).aspx)
- Apache 2.2 had some kind of ["Order" directive](http://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#order).
- Some other systems process ACE in order but if a conflicting **allow** rule is found after a **deny**, they ignore that **allow** rule.

In most cases, ACLs are defined by the developer in the code. In which case, it is her/his responsibility to order ACE properly. In the case of storing ACLs in a database, the developer should add some sort of mechanism to prevent (re)ordering ACE in a way that could introduce a security breach.

**Comment by mcdonc** [comment]
AFAIK, the concept of an access control list implies that the order of items (ACEs) in the list matters.  This is my understanding of what an access control list is.  The examples you gave seem to support this understanding, but then introduce something that purposely ignores that ordering for various reasons.

But I think debating the definition of "ACL" may be somewhat moot for these reasons:

1.  There is no chance we will change how the current ACL processing works, because it would break backwards compatibility in a critical area.

2.  It's not hard to maintain the order of something persistently, or at least it's not a NP-complete problem.

3.  If the developer can maintain the ordering of something, then he can introduce guards on top of the system that allows people to add/remove/reorder ACEs so they don't do "something bad".  I think this is a fair separation of responsibility.

4.  The system is pluggable.  If the current ACLAuthorizationPoicy does not do what you like, you can easily swap in an implementation that does.  Maybe one which treats the ACL as a set instead of a list.

**Comment by mcdonc** [comment]
Alternately instead of plugging a new policy in, ensure that deny ACEs always precede allow ACLs in any system that allows people to add/remove/reorder.

**Comment by bertjwregeer** [comment]
I like to imagine the ACL ruleset as a firewall that processes rules with first match wins. No overrides, nothing. This makes sense for me too. When storing entries in a database you may of course sort based upon any type of key or ordering you'd like, knowing that first match will win.

**Comment by jstoiko** [comment]
Thank you for your feedback gentlemen. This was very informative.
