### ISSUE TITLE
Create a top level pyramid command

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid#1868]
Currently there a number of commands that Pyramid provides, however each one is written as it's own independent command with nothing to tie them together except a convention that they start with the letter p. I think it would be better to deprecate these commands (but probably not remove them?) and instead move them as subcommands under a global ``pyramid`` command.

Reasoning:

The current situation sucks for discoverability, If I'm in my shell I don't have any real way to see what commands Pyramid provides except by typing ``p<tab>`` which is going to introduce a TON of noise (several hundred results) and the commands are generically named enough it's not obvious which ones are pyramid related. If there was a single top level command of ``pyramid`` then tab completing would make it obvious that this command was for interacting with pyramid. Additionally I could do ``pyramid -h`` to see a list of all of the available commands as well as a short description about what they actually do.

In addition, the current situation pollutes the global namespace of commands. This is unfriendly and messy. A top level command would reduce the polution and would be a good idea for the same reasons the import system has ``pyramid.httpexception`` and ``pyramid.config`` and not ``pconfig`` and ``phttpexception``.

My proposal would be to just take all of the existing ``p<cmd>`` commands, create a top level ``pyramid`` command, and move them each as ``pyramid <command>`` like ``pyramid serve`` etc. I would keep any existing commands but have them act as aliases for the ``pyramid <command>`` commands, but raise a deprecation warning recommending people switch to using the new command.

**Comment by kissgyorgy** [comment]
it has been this way long time ago: http://docs.pylonsproject.org/projects/pyramid//en/latest/changes.html?highlight=paster#id77

**Comment by marioidival** [comment]
Why not provide the two ways?

**Comment by mcdonc** [comment]
I doubt this will ever happen, as as @kissgyorgy says, this is the model we moved from when we replaced paster.  FWIW, if command discovery is an issue, a workaround that involves only documentation changes would be tell folks to not use "activate" in a virtualenv (I don't think any Pyramid docs tell people to do this right now anyway, because personally I never use activate) and do "bin/p<TAB>" to discover the appropriate commands.

I'm -0 on leaving the existing ``p*`` commands and providing an additonal ``pyramid`` wrapper command that invokes one of the various ``p*`` commands (e.g. ``pyramid serve`` would invoke ``pserve``), because I don't believe the people that we're trying to help would actually be helped by having more than one way to do this.

I'm going to close this, given that it's a sort of request for judgment, and I can't see doing it.

**Comment by sontek** [comment]
I'm +1 on this because telling people to type bin/p<tab> doesn't help either. 

```
$ bin/p
pbr          pip          preactivate  pshell       pyflakes     python
pcreate      pip3         prequest     ptweens      pyramid_cli  python3
pdistreport  pip3.4       proutes      pviews       py.test      python3.4
pep8         pipdeptree   pserve       pybabel      py.test-2.7 
```

I think it would be a much nicer user experience to type `pyramid --help` or something similar to figure out what is available.  A lot of people don't even realize there are commands outside of `pserve` but if the others showed up in `--help` they would

**Comment by mcdonc** [comment]
Afaict, everybody whom has commented within this issue so far knows what the commands are, or at least if they don't, they know where to look to find them in the docs.  If I'm wrong about that let me know, but if I'm not let's give other folks the same baseline benefit of the doubt.

**Comment by stevepiercy** [comment]
The p* commands are easy enough to find in the documentation. One of the more common requests of newbs is "How do I create a Pyramid project?". The answer is easy to find.
http://docs.pylonsproject.org/projects/pyramid/en/latest/search.html?q=create+pyramid+project&check_keywords=yes&area=default

I think it would be a nice little project outside of Pyramid, yet under the Pylons Project.

**Comment by dstufft** [comment]
Well, I found out about a bunch of commands that I didn't even realize existed by looking in the ``pyramid/scripts`` directory to take a look at how the ``pshell`` command was written. I'm not exactly a Pyramid expert but I'm not a novice either and I had no idea those commands existed. So I wouldn't exactly say that I knew what the commands were except that I discovered them by accident while source diving. I could probably locate them in the docs, *if* I knew that there was a command in particular I was looking for. As it is I hadn't realized that these commands existed because I didn't have a previous reason to look at them beyond pserve and pshell (which I discovered organically through the uh, getting started guides). Looking at the commands that were available there are commands here that would have been useful for me except I didn't realize they existed because I didn't realize they existed it never occured to me even look at the documentation to find what the commands were that I didn't know existed.

However I interact with the CLI of my programs constantly, and there is a very high chance that I would have seen that there were additional commands and then had that information available to me.

I don't think it makes sense for it to be a project outside of Pyramid because the commands themselves come from Pyramid, but more importantly since one of the main purposes would be to aid discoverability, having to first discover another project negates the primary benefit.

*Note: I say this would have helped me, because I have since I started moved away from the ``.ini`` files so all of the commands are more or less useless to me. I opened the issue because it would have made my experience better.*

**Comment by sontek** [comment]
@mcdonc I am aware of all of these commands but I work at a fairly large organization with 100 other Pyramid developers and I've had to expose many people to these commands and they are always grateful for my "tribal knowledge".

I don't think these commands should be tribal knowledge or rely on word of mouth or source diving for discovery.  If the workflow for a user was:

```
pyramid create <app> -t <template>
pyramid serve development.ini
```
I think they next thing they would do is `pyramid --help` to see what else they can do.

**Comment by sontek** [comment]
@stevepiercy I've been lobbying for the CLI/commands to be released outside of Pyramid proper but @mmerickel brought up a great point that a lot of the commands are depending on internal APIs and it wouldn't be practical to have them released outside of the pyramid because they could break version to version.

**Comment by inklesspen** [comment]
@sontek and others, FYI: in my work on montague I intend to release a `montague-pyramid` package that provides equivalents of the various `p*` commands that work with montague config loading.

I am increasingly liking the idea of a common `myramid` command in this package as well.

**Comment by sontek** [comment]
As a side-note,  I was not aware of all the commands available :)   I just discovered `pdistreport` by looking in the repo.  I've even worked on commands in that folder and hadn't noticed that one before!

**Comment by mcdonc** [comment]
OK, guess this isn't over. ;)

FWIW, here's where I'm coming from by -1'ing this.  The machinery for registering and creating console scripts already exists as part of setuptools, and it's one of the best features of setuptools.  It's simple, and it works great.  The downside is that the commands are separately invoked, and there's no centralized registry of pyramid-related commands to query.

I'm not saying this would necessarily be a bad thing to have.  Knowing "all these commands are related" is useful information.  But when you start getting in to creating an omnibus ``pyramid`` (aka ``paster``) command, you either have to inject another dependency (maybe something like Armin's ``click``?), or create and document another framework for registering subcommands into the omnibus thing, or just utterly hardcode things into some omnibus-related Python module that knows that there is a ``script`` command, a ``serve`` command, etc and the way that you add another is to edit that module.

I don't think it's a great idea to create another very general framework inside pyramid to register subcommands.  I was able to not port a good deal of ``PasteScript`` code because I just moved all the commands into setuptools console scripts instead of porting the finicky, frameworky, stream-of-consciousness-ny code that let people register ``paster`` subcommands (e.g. the stuff in the ``paste.script.command`` module).  PasteScript had some developer-facing docs in it about how to register more subcommands, but they aren't good enough to just steal and use in the Pyramid docs, even if we decided that the way that PasteScript offered that capability was a good thing to model on (which I don't think it is, I think it's pretty terrible).

It might be OK to reuse something that exists that already does this.  But it's going to add another dependency, and the documentation burden for is still nonzero.  I've learned that people always want stuff redocumented in a more specific context rather than asking them to read about a whole separate framework, and they're going to want to see a "How To Extend the ``pyramid`` Command With Custom Verbs" chapter in the docs if we made the feature possible at all.

We could just hardcode it entirely.  If we were to do this, the very best implementation might just be:

```
if __name__ == '__main__':
   alllowed = ['serve', 'create', 'routes', 'distreport']
   command = sys.argv[1].lower()
   if command in allowed:
       args = ' '.join(sys.argv[1:])
       cmddirpath = .. uh.. figure out some way to find the dirpath of the console script
       os.execv(os.path.join(cmddirpath, 'p' + command), sys.argv[2:])
   else:
       print('\n'.join(allowed))
```

I'm thinking something along those lines wouldn't be terrible.  If it's any more complicated than that, we'd probably be doing it wrong.  But note that the only thing it's adding of value is printing a list of the allowable commands.  And someone still would have to go through all the docs and decide whether or not to change ``pserve`` to ``pyramid serve`` in various places, and whether to explain the distinction, etc.  It'd be two ways of doing the same thing, and both would have to work indefinitely.  And of course even then someone will want to know how this all works, and some documentation about how the ``pyramid`` command works would need to be added even if it just exposes how terribly brutal it is.

@sontek if you're very confident that one of these options this would help a majority of the hundred folks you work with in a way that was much more meaningful than a docs page that listed the commands in a clearer way, I'd re-entertain the idea.  But I'm still skeptical that the people you're trying to help will actually be helped in any meaningful way, and we should figure out exactly what we're trying to help them do (are we trying to help them avoid reading docs?  what commands are we trying to lead them to, etc?)

**Comment by sontek** [comment]
@mcdonc Yeah, I would say the primary goal should be to expose the Pyramid provided commands in a nice discoverable way. If we had to make the decision that you aren't allowed to register your own commands inside it I think that would be a fine restriction, so the code example you provided above would work pretty well.

For the people I help at work, I don't think its about avoiding reading the docs but being able to work efficiently with the tools they have. I don't see HTML documentation a replacement for something like `--help` for a CLI command and a lot of times they don't know they are looking for a CLI command so they wouldn't really discover the docs they need.

We could significantly improve these docs http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/commandline.html so that it gives you a quick top level overview of the commands:

```
pcreate - Create a new application
pserve - Serve your application
proutes - List routes in your application
```

Which would be "enough".  

The biggest thing for me in training people about the Pyramid CLI is I have conversations like this:

`Dev`: "When I hit this route it gives me a 404 but it *is* registered!" 
`sontek: Lets check `proutes dev.ini` and view whats in there. 
`Dev`: "Wow! I didn't know that was possible"
`sontek`: "Oh yeah! There are all kinds of commands, check out `pviews`, `prequest`, and umm.. the rest, I forget what else is there".  

If instead I could be like "Oh yeah!  Check these out `pyramid --help` or link them to docs that gives a nice top level overview of what is available then it would be much easier for them to know whats available the next time they have a problem.

The two big ones I have to introduce people to all the time are `proutes` and `pshell`.  No one realizes they are available and the first time I have to help someone debug a problem and I use either it blows their mind.  I feel (obviously no scientific proof behind this) is that if someone typed `pyramid --help` one time and saw `shell` as an option, they next time they want to play with their pyramid code they would reach for that command instead of doing something like:

```
$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from app import hello
>>> from pyramid.testing import DummyRequest
>>> request = DummyRequest()
>>> hello(request)
```

which is what I see most of our devs doing.

**Comment by stevepiercy** [comment]
> We could significantly improve these docs http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/commandline.html so that it gives you a quick top level overview of the commands:

Something like this at the top of the page?

## List of commands

[pviews](http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/commandline.html#displaying-matching-views-for-a-given-url) - Displaying matching views for a given URL
[proutes](http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/commandline.html#displaying-all-application-routes) - Displaying all application routes

Additionally improve the content as follows.

1. Each command would be listed and have an anchor link to its heading and full description further down the page.
1. Each heading for the command would include both its name and its primary purpose. Currently just the function is shown as the heading.
1. Add new sections for commands whose descriptions are omitted.

Would this add too great a burden for doc maintenance or have some other negative impact?

I volunteer to work on this and take the lead. I'd create a new branch to make it easier for others to contribute, something like `docs.pcommands`. What do y'all say?

**Comment by mcdonc** [comment]
I think that would be fantastic, regardless of the outcome of some eventual software change!

**Comment by sontek** [comment]
@stevepiercy :+1:

**Comment by mmerickel** [comment]
I'm personally a big fan of a `pyramid` command for discoverability versus the individual top-level commands. The question is whether we support making it extensible, and I think even if we said "no" now we'd get a ton of requests for it in the future and would have to reconsider. This is where it gets hairy as far as compatibility etc. I'd propose something similar to what @mcdonc is suggesting where the commands themselves are still mostly independent but mounted into the same namespace allowing people to make third party packages that showed up there as well via setuptools entry points.
