### ISSUE TITLE
config.add_javascript_view raises `AttributeError`

### ISSUE THREAD

**Issue by AlbertEmil** [Pylons/pyramid#1890]
Referring to the [Cookbook](http://pyramid-cookbook.readthedocs.org/en/latest/pylons/static.html) there a specific methods to create static views for the three common folders

 - javascript (`config.add_javascript_view`)
 - stylesheets (`config.add_javascript_view`)
 - images (`config.add_images_view `)

However, calling them raises AttributeErrors like

 > pyramid/config/__init__.py", line 793, in __getattr__ raise AttributeError(name)
 > AttributeError: add_stylesheets_view

It should be mentioned that those methods do not seem to be documented in the [documentation](http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/assets.html).

**Comment by stevepiercy** [comment]
That page is not officially supported by Pyramid. It is also intended for former Pylons web framework users. Don't use it as a reference to learn Pyramid. Instead use the officially supported documentation and tutorials, listed under http://docs.pylonsproject.org/projects/pyramid/en/latest/#getting-started Specifically, you can refer to Step 13 in the Quick Tutorial http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/static_assets.html

**Comment by mmerickel** [comment]
@AlbertEmil those should all read `config.add_static_view`, you're right. However the issue belongs in the cookbook repo.

**Comment by sontek** [comment]
@stevepiercy If this isn't officially supported by pyramid why do we have it?  Who is to say that @AlbertEmil isn't a former pylons web framework user?

I don't think closing this issue so was the proper way to resolve this problem, the information in that documentation is completely invalid Pyramid doesn't provide those functions out of the box. We should just move it over to the cookbook repo ( https://github.com/Pylons/pyramid_cookbook )

Is there an extension that provides them?  If so we need to add that to the docs.  If not we need to remove those lines from the docs.

**Comment by stevepiercy** [comment]
@sontek It's my understanding that the cookbook is "community supported", not "officially supported", similar to [PYramid Tutorials](http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/). The reason is because it is too great a burden to maintain every recipe and tutorial outside of the official docs, keeping every recipe up to date with the releases of the latest versions of Pyramid. Directing the user to the official version of the docs and tutorials is proper.

@AlbertEmil [cross-posted stating](http://stackoverflow.com/questions/32425388/pyramid-static-views-js-img-css-attributeerror) "Since I am a beginner using Pyramid...".

**Comment by sontek** [comment]
@stevepiercy The cookbooks are still controlled under the pylons organization and if there is a problem with the documentation its up to us (the community) to fix it.  

If we plan on turning people away and closing their issues because they landed on the cookbook docs that provide bad information then we should remove their branding and move them to a different github organization to make it clear that they aren't maintained/supported.

We should also provide a disclaimer on the top letting users know that they should use those docs at their own risk.

**Comment by stevepiercy** [comment]
@pauleveritt and @blaflamme should be involved in this conversation.

Welcome to the can of worms!

This is a branding issue because we lack a Sphinx theme that is explicitly and clearly "Pylons Project". We've slapped the cookbook and tutorials repos with the "pyramid" Sphinx theme because it is the least incorrect choice of the three available Sphinx themes (pylons and pylonsfw being the other two).

There is value in keeping the cookbook and tutorials under the Pylons Project. We need to be more transparent about how these supplementary docs fit into the official docs. We also need the who/how/when/why they will be maintained.

A "Pylons Project" Sphinx theme for the cookbook and tutorials would avoid some confusion.

I agree a disclaimer would be appropriate.

We should direct people from the cookbook and tutorials to the official docs when that is appropriate, too.

So how do we do both?

I think it would be too great a task to go through all the tutorials and recipes on a per item basis. Per repo/site is doable.

We need to consider that some items in both repos are relevant to solving a specific task beyond the official Pyramid docs, like all the [Deployment recipes](http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/deployment/index.html) or [Quick Tour for Traversal](http://docs.pylonsproject.org/projects/pyramid_tutorials/en/latest/quick_traversal/index.html).

One option would be to use an indicator like we have on [older versions of Pyramid docs](http://docs.pylonsproject.org/projects/pyramid/en/1.4-branch/index.html), similar to the friendly red button.

The implementation should not scroll out of view.

**Comment by pauleveritt** [comment]
Steve said it perfectly. I think we need to be very careful about loading all the documentation and code maintenance work in the the Pyramid “core”. I think resources and obligations there are already thin. IMO, the Pylons/pyramid repo should get smaller, including the docs. Like Steve said, we should have other software and documentation that is unofficial, community-maintained, and branded as such.

He’s right, the Sphinx theme has been the challenge.

—Paul
