### ISSUE TITLE
Document interaction of .override_asset() with .add_translation_dirs() and others

### ISSUE THREAD

**Issue by piotr-dobrogost** [Pylons/pyramid#2046]
It looks like `.override_asset()` is not effective in the subsequent `.add_translation_dirs()` unless `.commit()` is called between these two calls. However I can't find this stated neither at http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/assets.html#assets-chapter nor at http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.override_asset
I think interaction of `.override_asset()` with other directives should be described in documentation.

**Comment by stevepiercy** [comment]
@piotr-dobrogost please check against the [master branch](http://docs.pylonsproject.org/projects/pyramid/en/master/narr/assets.html#overriding-assets). After doing so, please suggest an improvement either on `master` (same as `1.6-branch`) or `1.5-branch` (which RTD renders as "latest". (The mapping of RTD URLs to branches on GitHub is not obvious at first.)

**Comment by piotr-dobrogost** [comment]
@stevepiercy 
If you mean I should check docs in master branch then there's no difference with regard to this issue. Before suggesting any changes to docs I would like to know if current behavior is by design or by accident. If the latter I would rather raise another issue suggesting to fix it (although as backwards incompatible I guess there's no chance to eventually fix this).

**Comment by disko** [comment]
I think there's a bug in the current implementation of ``add_translation_dirs``.

Consider this code:

    config.override_asset('some.package', 'other.package')
    config.commit()
    config.add_translation_dirs('some.package:locale')

If ``some.package`` contains a ``locale`` directory but ``other.package`` does not, a ``pyramid.exceptions.ConfigurationError: "<path-to-other.package>/locale" is not a directory`` will be raised.  This is caused by first splitting the asset spec, then concatenating the package path and the file name (https://github.com/Pylons/pyramid/blob/master/pyramid/config/i18n.py#L83).  In the example above ``package_path(package)`` will be the absolute path of ``other.package``, which doesn't contain a ``locale`` directory and hence raises the exception.

If https://github.com/Pylons/pyramid/blob/master/pyramid/config/i18n.py#L81-L83 would be ``directory = pkg_resources.resource_filename(package_name, filename)`` instead, everything should work as expected, also with asset overrides in place. 

Also see https://github.com/Kotti/Kotti/issues/475.

**Comment by mmerickel** [comment]
@disko Could you please submit a fix with a failing unit test? In Pyramid 1.6 we also support overriding absolute paths so there may be some issues there that it would be helpful if you could investigate. I think your fix makes sense though.

**Comment by mmerickel** [comment]
I agree that `add_translation_dirs` should be using an `AssetResolver` to discover the locations. We should also adjust the PHASE of `override_asset` such that it occurs in an earlier cycle than `add_translation_dirs` which would ensure that the order no longer matters between the two.

Another subtle issue that I'm trying to understand is why asset overrides work at all. It looks like it only works if the package itself is overridden, but not the folder name inside the package. For example, I expect `override_asset('some.package:locale/' 'other.package:not_locale/')` to fail because it isn't passing the folder name through any asset resolution path... only the package name itself.

Finally, this only works because kotti is calling `config.begin()` to push the threadlocale asset resolver into `pkg_resources`. This won't work in other pyramid apps without calling `config.begin()` (or proposed #2872). This should also be documented better.

2 bugs and bad docs! Lots to fix!
