### ISSUE TITLE
pserve --reload should use inotify or equivalent when available

### ISSUE THREAD

**Issue by JonnoFTW** [Pylons/pyramid#2081]
After reading the pserve code it appears that using the `--reload` flag makes a loop that runs every second (with adjustable times) which runs stat against all relevant files. This is a waste of resources, since linux provides the inotify system.

The offending code is in this function:

https://github.com/Pylons/pyramid/blob/master/pyramid/scripts/pserve.py#L863

A potential fix might require a FS monitoring library like [watchdog](https://pythonhosted.org/watchdog/) which handles these invents in an OS independent manner.

**Comment by stevepiercy** [comment]
Please consider the following points.

* The behavior is not broken.
* `--reload` is only useful during development. It's merely not efficient as you would like in development where inefficiency is not a high priority. If the current behavior impedes development work, then that would be a good argument.
* I don't think more dependencies is a good idea, and Pyramid has been shedding them in order to be efficient where it matters most.

I would be interested in seeing how you would implement your suggestion, preferably through a PR on a new branch.

I think this might be a candidate for the [Pyramid Cookbook](http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/), perhaps with benchmarking comparisons.

**Comment by bertjwregeer** [comment]
To add another point to Steve's list, Pyramid is heavily developed on not just Linux but also Mac OS X where `inotify` does not exist.

Windows is another target that we have to keep in mind, thus making changes that are tied to a single operating system makes things more difficult to debug.

That being said, `pserve` is a simple script that you are free to take, and modify as you see fit. It is a runner that ultimately just starts a WSGI server. If you would like you could provide `pyramid_linux_pserve` as a package that implemented your changes.

**Comment by mmerickel** [comment]
Adding an optional dependency on watchdog isn't a bad idea. We could add it as an `extras` on pyramid install and pserve could use it if available. Watchdog itself is cross platform.

**Comment by JonnoFTW** [comment]
@bertjwregeer I mentioned watchdog because it is cross platform. I'll make a package and see how it goes.

**Comment by domenkozar** [comment]
It depends on `PyYAML >=3.10', 'argh >=0.24.1', 'pathtools >=0.1.1`

**Comment by mmerickel** [comment]
related #2250

**Comment by bertjwregeer** [comment]
This issue has been resolved with #2805 which uses `hupper` which can use `watchdog` to look for changes.
