### ISSUE TITLE
Snippet of code missing in testing docs

### ISSUE THREAD

**Issue by sontek** [Pylons/pyramid#2124]
The line of text says:

```
You'd then create a tests module within your myproject package, containing the following test code:
```

but then there is no code there.

The link is here:

http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/testing.html

Seems to be a build issue because when I build the docs locally the code is there and its there on the 1.6 branch docs as well.

**Comment by stevepiercy** [comment]
I can repeat this locally. This appears only on RTD across at least three branches: master, 1.6-branch, 1.5-branch. I'll open an issue there.

**Comment by stevepiercy** [comment]
It turns out that the source code was never added to the file which the `literalinclude` calls. So I added it to the [master branch](http://docs.pylonsproject.org/projects/pyramid/en/master/narr/testing.html#creating-integration-tests).

But then [I tried following the example in the docs](https://github.com/Pylons/pyramid/issues/2172), and now we've realized that the [integration test is wrong](https://github.com/Pylons/pyramid/issues/2172#issuecomment-163991919). I'm going to close this issue and the RTD issue as well.

If anyone cares to add a working integration test, please follow up in #2172.
