### ISSUE TITLE
Update official tutorials to use one-way encryption for authentication steps

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2204]
The updated tutorial [Pyramid Blogr](http://pyramid-blogr.readthedocs.org/en/latest/registration.html) uses `passlib` and has a [warning about best practices](http://pyramid-blogr.readthedocs.org/en/latest/basic_models.html?highlight=encryption#update-database-initialization-script). The following tutorials should be modified to implement this best practice.
- [x] http://docs.pylonsproject.org/projects/pyramid/en/master/tutorials/wiki2/authorization.html
- [x] http://docs.pylonsproject.org/projects/pyramid/en/master/tutorials/wiki/authorization.html
- [x] http://docs.pylonsproject.org/projects/pyramid/en/master/quick_tutorial/authentication.html

**Comment by RaHus** [comment]
The authorization tutorial and the authentication quick tutorials are using hard-coded values for a user database, i guess because the intent is to showcase pyramid features and not webdev best practices, so password encryption is not exactly applicable IMO.

Is the intent of this ticket to switch the tutorials to use permanent storage? and if so, which would be a good choice given the requirements of the tutorials?

**Comment by stevepiercy** [comment]
@RaHus all these tutorials use persistent storage at some point. Currently these tutorials lack sufficient notice about encryption and omit examples of best practices, which gives a very misleading message about security: "unencrypted passwords are OK". We should do a lot better.

I think what we will end up doing is creating a single page, either in the main documentation or in the Pyramid Community Cookbook, that gives example for security best practices.

**Comment by RaHus** [comment]
@stevepiercy I agree, the tutorial code should stick to best practices, i am just saying that the way the auth tutorials are written you'll have to make extra changes for them to use persistent storage in addition to the encrypted password changes.
in http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html 20 and 21 are based on code from 09, also 18 and 19 are based on 09. One solution would be to base 20 and 21 on 19.

**Comment by stevepiercy** [comment]
I'd love to review something concrete: PR, gist, whatever. Contributing to docs has some challenges, and I'm happy to help out.

The grant-worthy label is to identify those issues or PRs that are considered worthy to be part of a grant application. We're looking into possibilities of funding sources to help make certain items a higher priority.

**Comment by mmerickel** [comment]
The wiki2 tutorial was updated to use bcrypt here. If anyone wants to copy that pattern to any other tutorials they are welcome to do that. I personally do not like passlib very much because 1) I find the api to be verbose and 2) it calls one-way hashes "encrypting" when it is definitely not using a bi-directional encryption algorithm.

**Comment by mmerickel** [comment]
It looks to me like all of the tutorials have been updated.
