### ISSUE TITLE
config.add_route(), traverse arg - no effect

### ISSUE THREAD

**Issue by artszk** [Pylons/pyramid#2335]
some python code in attachment.
[test.txt](https://github.com/Pylons/pyramid/files/118089/test.txt)

When I'm trying http://127.0.0.1:6543/search/a 
... everything seems ok: request.traversed -> (u'a', )
But when: http://127.0.0.1:6543/search/a/b
... I get NotFound. No any __getitem__ calls

The fallowing working properly
config.add_route('search', '/search/*traverse', factory=ParamRootFactory)

**Comment by mmerickel** [comment]
`{params}` only matches a single path segment. `*traverse` is appropriate if you want to treat every segment as a traversal node.

**Comment by artszk** [comment]
In that case, path like '/some/1/2/3/edit' not match to route entry: 
`add_route('/some/{params}/edit', traverse={params})` ? 
Sorry, I improperly suggested to: [doc](http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/api/config.html?highlight=add_route#pyramid.config.Configurator.add_route) (traverse part).

**Comment by artszk** [comment]
... but '/some/1/2/3/edit' match to:
`add_route('/some/{param1}/{param2}/{param3}/edit', traverse='/{param1}/{param2}/{param3}')` ?

**Comment by mmerickel** [comment]
Your examples in the last 2 comments are correct. The default regex for a pattern parameter only spans one path segment except for the special `*foo` which will result in a `matchdict` item named `foo` containing a tuple of segments. Naming it `*traverse` has the added benefit that it is forwarded into traversal.

To summarize, it's expected behavior that `/some/{params}/edit` will not match `/some/1/2/3/edit`.

**Comment by artszk** [comment]
All clear, thanks. Next time I won't so fast to add an entry to Issuses ;)
