### ISSUE TITLE
pip install pyramid does not have correct version dependency for zope.interface

### ISSUE THREAD

**Issue by rabinnh** [Pylons/pyramid#2377]
Just installed Pyramid on Ubuntu 14.04 via pip.  All dependencies satisfied. On running the tutorial I get this error:

Traceback (most recent call last):
  File "./pyrtest.py", line 4, in <module>
    from pyramid.config import Configurator
  File "/usr/lib/python2.7/dist-packages/pyramid/config/__init__.py", line 12, in <module>
    from pyramid.interfaces import (
  File "/usr/lib/python2.7/dist-packages/pyramid/interfaces.py", line 3, in <module>
    from zope.interface import (
ImportError: No module named interface

This dependency appears to be missing.

**Comment by piotr-dobrogost** [comment]
`zope.interface` is listed in dependencies here https://github.com/Pylons/pyramid/blob/master/setup.py#L45

**Comment by rabinnh** [comment]
Very true.  I saw that.  But I had to run:

pip install -U zope.interface

to fix the error.  So apparently 1.6.1 it needs a newer version:

home:~$ pip freeze | grep pyramid
pyramid==1.6.1

home:~$ pip freeze | grep zope
zope.deprecation==4.1.2
zope.interface==4.1.3

**Comment by mmerickel** [comment]
This sounds like some sort of path issue with how you were using your virtualenv. Maybe you can paste a full session from start to finish of:

- make a virtualenv
- install pyramid
- pcreate new project
- cd project
- make a virtualenv
- install project deps

**Comment by rabinnh** [comment]
Ok, then, my misunderstanding.  I didn't realize that Pyramid only works in a virtualenv environment.  I was installing it on a Web server.

**Comment by rabinnh** [comment]
Still, thinking about it, I did have zope.interface >3.8 installed and updating it solved the problem.  Doesn't that imply that the dependency version should be bumped?

**Comment by pauleveritt** [comment]
I don’t think @mmerickel means it requires a virtualenv. Rather, he wants to reproduce a pristine environment. A fresh Docker container or VM could do the trick equally well in showing a reproducible case.

—Paul

**Comment by mmerickel** [comment]
You said you were following the tutorial so I was asking you to paste an exact recreation of the steps done in the tutorial (because it should work). If you've deviated from that then you need to show us what you're doing. Obviously you've deviated from it if you aren't using a virtualenv.

If you aren't using a virtualenv then you are susceptible to the system dependencies already installed in the system python including possibly zope.interface which is used for many projects. Thus your system probably has an old version and since you didn't install anything with `-U` originally it didn't upgrade the system install of zope.interface - thus your error.

You should always use a virtualenv to isolate yourself from these issues. Unknowingly upgrading packages that your system uses could break your entire system.

**Comment by mmerickel** [comment]
Is there anything more to be said on this issue @rabinnh?

**Comment by bertjwregeer** [comment]
Do we need to pin the `zope.interface` version to something that is greater than 3.8 I think is the question being asked.

**Comment by mmerickel** [comment]
> Do we need to pin the zope.interface version to something that is greater than 3.8 I think is the question being asked.

Yeah I don't think we have any action items until we know exactly what is wrong with @rabinnh's current environment. Something zope-y is installed since it didn't complain about `zope` but rather the subpackage `interface`. The rest is just guessing and I imagine using a fresh virtualenv will solve the issue.

**Comment by mmerickel** [comment]
Please feel free to reopen if you have more information to share.

**Comment by johnlinvc** [comment]
We got this issue when trying to deploy pyramid to AWS lambda,
Turns out `zope.interface` is in `lib64`, but other `zope` libraries are in `lib`.
copy both `lib/python2.7/site-packages` and `lib64/python2.7/site-packages` into single `site-packages` solve the problem for us.

error trace
```python
Traceback (most recent call last):
  File "/var/task/main.py", line 11, in handle
    from pyramid.request import Request
  File "/var/task/site-packages/pyramid/request.py", line 4, in <module>
    from zope.interface import implementer
ImportError: No module named interface
```

**Comment by bertjwregeer** [comment]
lib64 should be a symlink to lib, however for some reason the Python version installed on Amazon machines doesn't correctly do this.

There is a longer thread with similar issues on Python 3.4 on Amazon's AWS EC2 images:

https://groups.google.com/forum/#!searchin/pylons-discuss/aws%7Csort:date/pylons-discuss/MSAMBzwx7aQ/lXer6kcNBwAJ
