### ISSUE TITLE
Answer "Why use $VENV/bin/pip instead of source bin/activate?"

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2610]
A common question in IRC is "Why do the tutorials use $VENV/bin/pip instead of source bin/activate, then pip?" Add an info box to explain they are essentially the same, but we chose the former for providing explicit context to commands.

**Comment by tseaver** [comment]
Also, `source bin/activate` drops turds in the user's shell environment, leaving them vulnerable to executing commands in the wrong context.

**Comment by ztane** [comment]
it could rather state that the $VENV/bin/pip just is to clarify that we run the pip from the venv and not system-wide.

However another thing to consider is that there are users who are unfortunate enough to use Pyramid on Windows, and there it doesn't help much to say that $VENV/bin/pip is unix-y, because it just doesn't work.

**Comment by bertjwregeer** [comment]
@ztane The docs show how to use `%VENV%\Scripts\pip` instead on Windows.

So that's not a concern.

**Comment by stevepiercy** [comment]
I have a revision that incorporates @ztane's remarks. I dropped the UNIX-y argument because what it means to be UNIX-y is subjective. I found that Sphinx supports emoji for "dropping turds" 💩 . Will update late tonight. Thanks for the feedback.
