### ISSUE TITLE
Tweens & pshell

### ISSUE THREAD

**Issue by canni** [Pylons/pyramid#2737]
I just stumbled upon the fact that request does not go through tweens stack, when one is using `pshell`

I'd like to bootstrap discussion on this :) Should we execute tweens in a shell?

_My use-case_

I'm using a custom dependency injector container, which bootstraps various services in global and request scope, usually the request scope is "entered" & "left" using a `with` statement in a tween.

I wanted to test something out quickly in `pshell` and I discovered that `request` scope is not active, although I have a (dummy, but still) a `request` object, a surpricing behaviour

**Comment by mmerickel** [comment]
related https://github.com/Pylons/pyramid/issues/520

I'm not against improving this situation, but doing it is not super straightforward and there are a lot of drawbacks to changing it. You start relying on all your tweens and events not having any side-effects (like writing to the database). Otherwise your database gets changed every time you launch pshell.. doing that is not a good design. Right now you get a request object with extensions but it doesn't go through the rest of the pipeline (think of it as dropping you into a shell right at the entrance of the request pipeline).

You might experiment with what you can / can't do with the setup hook on pshell and maybe we can improve that somehow.

**Comment by ztane** [comment]
Negative, got pyramid_tm; being within pyramid_tm in pshell would make pshell unusable.

**Comment by mmerickel** [comment]
Thanks for the issue report. I'm going to close because I haven't seen any compelling reasons to execute the tween pipeline for pshell.
