### ISSUE TITLE
Automate releases via Travis?

### ISSUE THREAD

**Issue by tseaver** [Pylons/pyramid#2751]
E.g., see the [Travis config for the project for my day gig](https://github.com/GoogleCloudPlatform/gcloud-python/blob/a310ca92c3433742eab87fe55b3ee7e19a8abbb0/.travis.yml#L20-L31).

**Comment by mmerickel** [comment]
Another example is here, which also runs bdist_wheel: https://github.com/pypa/setuptools_scm/blob/master/.travis.yml#L16

I really don't like that the pypi metadata becomes sticky to one pypi account, instead of the maintainer actually doing the releases. I'm also pretty jittery in general about even storing encrypted credentials in the cloud. I'm not sure how revocable they are if I move on in the future... do I have to change my pypi password, or can anyone find the git history and pull out those credentials and use them with travis? Even if it's just someone with access to the pylons org on travis, that's still a lot of people who could reuse those credentials.
