### ISSUE TITLE
wiki2 tests on master have import errors

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2882]
Ref: https://github.com/Pylons/pyramid/pull/2855#issuecomment-268483317

On the `master` branch, after running through the wiki2 tutorial from a cookiecutter or scaffold, then running the tests in the Adding Tests step, there are import errors. To save time, one could follow these steps to reproduce:

* http://docs.pylonsproject.org/projects/pyramid/en/master/tutorials/wiki2/installation.html
* overwrote my generated tutorial files with those from https://github.com/Pylons/pyramid/tree/master/docs/tutorials/wiki2/src/tests
* ran `pip install -e ".[testing]" to install dependencies
* then pickup from my above transcript, starting with `$VENV/bin/py.test -q`

I did not install the `mock` package (it was not included in instructions or setup.py), so I had to change the imports.

Here's the traceback.

```python
$VENV/bin/pytest -q

========================================================================== ERRORS ==========================================================================
______________________________________________________ ERROR collecting tutorial/tests/test_initdb.py ______________________________________________________
ImportError while importing test module '/Users/stevepiercy/projects/__pcs/tutorial/tutorial/tests/test_initdb.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tutorial/tests/test_initdb.py:1: in <module>
    import mock
E   ImportError: No module named 'mock'
_____________________________________________________ ERROR collecting tutorial/tests/test_security.py _____________________________________________________
ImportError while importing test module '/Users/stevepiercy/projects/__pcs/tutorial/tutorial/tests/test_security.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tutorial/tests/test_security.py:1: in <module>
    import mock
E   ImportError: No module named 'mock'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2 error in 1.01 seconds
```

**Comment by mmerickel** [comment]
The issue is that as @zupo said, python 3 has `unittest.mock` but python 2 does not and requires a dependency.

There is no good solution here other than to stop using mock. In real projects it's totally fine for people to use it, but we don't want the scaffolds to do weird 2 vs 3 importing tricks - no one is developing an app from a scaffold that must run on both and the scaffold shouldn't get them started in this direction.

Since we are still supporting python 2.7 in the scaffolds the only real option here is to come up with alternative test implementations using dummy objects and stop relying on the mock module.

**Comment by zupo** [comment]
Makes sense!
