### ISSUE TITLE
WebOb silent upgrade breaking production site

### ISSUE THREAD

**Issue by hyperknot** [Pylons/pyramid#2892]
I've run into braking changes in WebOb 1.7, which was silently upgraded in my Pyramid app, as I didn't pin WebOb specifically to 1.6. I've opened this ticket for WebOb and got a very helpful and detailed answer for it: https://github.com/Pylons/webob/issues/304

However, I would like to raise the point that how WebOb + Pyramid handled this upgrade, potentially many sites broke or will soon brake after the holidays when people will first deploy.

1. There were absolutely no depreciation warnings about this change, only a tiny `# deprecated` comment in the source code. Nothing visible at all even in an environment with `PYTHONWARNINGS=default`.

2. Pyramid had no pinnings for WebOb, only a minimal version of `WebOb >= 1.3.1`. So this change just silently upgraded WebOb for every project where WebOb was not pinned. And why would anyone have it been pinned, as it's a sub-dependency of Pyramid, nothing a developer should worry about.

I believe the core point is trust here. A project, especially a core project of an app like Pyramid should make sure that by pinning an exact release, core stuff like the Response() object is guaranteed not to brake. A developer is trusting the Pyramid project to handle sub-dependencies in a way that his site will not brake because of any changes there. 

Note: in my small app, I am manually managing versions for 34 dependencies, which expand to 107 dependencies on a `pip freeze`. No developer should ever be asked to try to follow recursive dependencies - that is trying to read about all 107 packages used with `pip freeze`, it's quite a big thing to manually follow and pin those 34 projects on their own.

**Comment by piotr-dobrogost** [comment]
That the Pyramid should monitor its dependencies for the breaking changes is one thing and that you should pin all dependencies yourself (especially on production) is another one. You don't have to follow any dependencies manually as there are tools created for this. See [pip-tools](https://github.com/nvie/pip-tools/) and [Pin Your packages](http://nvie.com/posts/pin-your-packages/).

**Comment by tseaver** [comment]
@bertjwregeer responded to this claim on https://github.com/Pylons/webob/issues/304.

**Comment by bertjwregeer** [comment]
@tseaver While I have responded on the other ticket, there is still the question as to whether Pyramid should on it's release be pinning versions of it's dependencies or not.

I don't think it should, but I understand how the changes I made to fix various issues in WebOb (that were reported on the issue tracker, and on IRC, and via email) could potentially break Pyramid users that weren't expecting it.

Best practices dictates that for production versions are pinned, using a tool like pip freeze so that you know what you are getting.

@hyperknot Regarding: 

> Note: in my small app, I am manually managing versions for 34 dependencies, which expand to 107 dependencies on a pip freeze. No developer should ever be asked to try to follow recursive dependencies - that is trying to read about all 107 packages used with pip freeze, it's quite a big thing to manually follow and pin those 34 projects on their own.

No, for your production you pip freeze at any given moment in time. Now in development you use those frozen dependencies until such a time that you can upgrade, at which point you start a new clean environment, download all of your projects dependencies, unfrozen, and test, make fixes, pip freeze again and then upgrade production to the new frozen dependency list.

No-one is suggesting you walk through each of those dependencies one by one to see if you can upgrade it.

Pyramid is built up out of multiple packages, you compared it to Django in the WebOb ticket and unfortunately that doesn't work. Django is a single package, and if you don't use third party tools with it, then it will never have any dependencies that need upgrading.

Django only has as extra's `bcrypt` and `argon2`, and both of those are not pinned at all, so potential changes to either of those could affect your Django experience, you are still expected to pin things yourself:

See here: https://github.com/django/django/blob/1.10.4/setup.py#L50

**Comment by hyperknot** [comment]
> test, make fixes, pip freeze again 

But how would I know what I need to test? Two solutions I could think of:
- Try to write tests for every single case (not just 100% line coverage, but anything what could possibly change in a production deployment of a web app, which would be an insanely huge list, possibly no human can ever think ahead).
- Try to test everything manually. That's also quite an impossible thing to do, only it would now need to do tests manually.

In this case there wasn't even a single depreciation warning which I would ever had a chance of seeing before running into the deprecated state.

I totally understand the different concept between Pyramid and Django, but at the end, I believe the end user doesn't care how a framework decides to handle sub-dependencies, all they care about is a stable and reliable setup they can trust, with depreciation warnings and documented upgrade paths between each release.

**Comment by bertjwregeer** [comment]
> Try to write tests for every single case (not just 100% line coverage, but anything what could possibly change in a production deployment of a web app, which would be an insanely huge list, possibly no human can ever think ahead).

No, write tests for your app. Changes to libraries that don't affect your app, no problem.

**Comment by piotr-dobrogost** [comment]
All being said there is some truth in that users do not really know what they get when there's no information on versions of dependencies the given version of Pyramid was tested with. It would be nice and convenient if Pyramid would document exact versions of all dependencies tested to work. For example Kotti does include requirements.txt file which does exactly this – https://github.com/Kotti/Kotti/blob/master/requirements.txt

**Comment by bertjwregeer** [comment]
@piotr-dobrogost we will happily accept pull requests for adding additional documentation (however unless someone commits to updating this documentation moving forward, I don't see how that would solve anything), however `requirements.txt` is not something we will be shipping.

**Comment by mmerickel** [comment]
The suggestion from kotti as far as I can deduce is to basically freeze dependencies at the time of pyramid release, ensure tests pass with those deps, and document that if you want to you can copy those deps into your own app if you wish. Travis then continues to run with those frozen deps and prior to each release it'd be updated. This would be a list of "supported" versions.

I'd have to chew on this some more. It's interesting, but pretty much just adds more work for maintainers and I'm not sure if anyone would actually use it because they'd still need to manually copy that file, or care enough to look at it.
