### ISSUE TITLE
HTTPException ability to prioritize application/json over text/html

### ISSUE THREAD

**Issue by loicgasser** [Pylons/pyramid#2987]
Hi,

I was wondering if it would be possible to prioritize json formatted response type over text/html on demand.

Looking at the code, it seems to me that this would not be too hard (works just fine locally):
https://github.com/Pylons/pyramid/blob/master/pyramid/httpexceptions.py#L256

At the moment without explicitly setting the `Accept` header in the request header, we can't define a default behaviour for our http response content type formatting.

Maybe via an additional argument in HTTPException?

Does this make sense to you?

**Comment by loicgasser** [comment]
This is roughly what I have in mind:
https://github.com/Pylons/pyramid/compare/master...loicgasser:default_ctype

**Comment by bertjwregeer** [comment]
You switched the order of the default from text/html, application/json to application/json, text/html. That breaks backwards compatibility.

If you want to have more control over exceptions, I would recommend something like the following code:

```
@view_config(
    context=HTTPException,
    exception_only=True,
    )
def reterror(context, request):
    if context.detail:
        context.json_body = {'error': context.detail }
    else:
        context.json_body = {'error': 'Unknown error'}

    return context
```

Then when you raise any `HTTPError`'s you can provide `detail`:

```
raise HTTPForbidden(detail='You are not allowed to modify this resource')
```

Since the exception view is a view like any other, you can use it to customise the errors to your liking.

I am a huge :-1: against adding more arguments to `HTTPException` to force a certain type of response. The current `Accept` handling that was added was added in a backwards compatible way, to prioritise `application/json` would break that backwards compatibility.

----

Set `Accept` in your requests, so that the client gets explicitly what they asked for.

If you want, write a Pyramid tween or WSGI middleware that modifies the incoming request and updates the WSGI environment to set the most appropriate `Accept` header. For example, if no `Accept` header is included in a request, explicitly set it to `Accept: application/json, text/html` with:

```
request.accept = 'application/json, text/html'
```

I believe that should even work with the above `@view_config`:

@view_config(
    context=HTTPException,
    exception_only=True,
    )
def reterror(context, request):
    # Determine if the request should send back as JSON
    if not request.accept:
        request.accept = 'application/json, text/html, */*;q=0.5'
    return context
```

**Comment by loicgasser** [comment]
Ok I get it thanks for your answer. I am clearly not aware of.
I am just pushing it because it is more and more popular to return json formatted error. And I was trying to define it once somewhere and be done with it.

You're probably missing the use case where other people want to call your API and excpect JSON error responses per default.

> Your default_content_type change also breaks other users that expect that the HTTException has a content_type already associated with it, if they set their own body (as in prepare() does nothing since it already has a body, with your change the content_type on the exception would be non-existent).

yes this should be (['text/html', 'application/json') and therefore wouldn't break anything.

Couldn't we add it define it when initializing the app?

**Comment by loicgasser** [comment]
Is ```exception_view_config``` the same as ```@view_config(exception_only=True``` ?

**Comment by bertjwregeer** [comment]
> You're probably missing the use case where other people want to call your API and expect JSON error responses per default.

No, I am not missing this use case. It is covered in the `@view_config` I included.

>Is `exception_view_config` the same as `@view_config(exception_only=True` ?

Yes. I just tend to have `view_config` imported and not the specialisation...

http://docs.pylonsproject.org/projects/pyramid/en/latest/api/view.html#pyramid.view.exception_view_config

**Comment by loicgasser** [comment]
With this solution
```
@view_config(
    context=HTTPException,
    exception_only=True,
    )
def reterror(context, request):
    if context.detail:
        context.json_body = {'error': context.detail }
    else:
        context.json_body = {'error': 'Unknown error'}

    return context
````
code and status_code are always 520 the default of HTTPException

Moreover I would have double validate the request header `Accept`

I am not saying you guys should implement it in `HTTPException`, it was really just a shot in the dark from my side, but maybe that the situation is not ideal.

**Comment by loicgasser** [comment]
> Moreover I would have double validate the request header Accept

this is not correct.

**Comment by loicgasser** [comment]
ok my bad, thanks again for taking the time to answer prepare is called twice apprently.
