### ISSUE TITLE
bad link on docs.pylonsproject.org search page

### ISSUE THREAD

**Issue by absente** [Pylons/pyramid#3026]
Recently I use the html version searching the document and found that, for example:
http://docs.pylonsproject.org/projects/pyramid/en/latest/search.html?q=cache_max_age

In result, the link of `pyramid.config` will refer to:
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.rst.html?highlight=cache_max_age

However that's a wrong place now. The true URL is this one:
`http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html?highlight=cache_max_age`
which the end of URL **without** the `.rst` extension name in the middle.

This problem also found on pyramid_cookbook's document search page and some else.

**Comment by mmerickel** [comment]
This is known[1] and is something we cannot fix on our own unfortunately. I'll leave this issue open to track it however. Thanks for the report!

[1] https://github.com/rtfd/readthedocs.org/issues/2708

**Comment by mmerickel** [comment]
It looks like we could pin to sphinx 1.4 but I'm not sure if we're depending on anything in 1.5 at this time.

**Comment by stevepiercy** [comment]
We would also need to pin to docutils 0.11 because [sphinx < 1.5 does not pin it to a compatible version of docutils](https://github.com/sphinx-doc/sphinx/issues/3212#issuecomment-283756374). I'm inclined *not* to change our `setup.py` for this issue. But if we want to...

```python
docs_extras = [
    # Pin Sphinx to 1.4.*  and docutils to 0.11 due to search issues with RTD:
    # https://github.com/rtfd/readthedocs-sphinx-ext/issues/25
    # https://github.com/sphinx-doc/sphinx/issues/3212#issuecomment-283756374
    'Sphinx == 1.4.*',
    'docutils == 0.11',
```

Here's the issue being tracked by RTD folks:
https://github.com/rtfd/readthedocs-sphinx-ext/issues/25

I've subscribed to both issue threads, so I'll get notification of any updates.

**Comment by stevepiercy** [comment]
YAY! Fix is coming this week!
https://github.com/rtfd/readthedocs.org/issues/2708#issuecomment-300323534

**Comment by stevepiercy** [comment]
This is now fixed.
https://github.com/rtfd/readthedocs.org/issues/2708
