### ISSUE TITLE
Q:  Why does the pyramid.request object have no `content_encoding` attribute ?

### ISSUE THREAD

**Issue by jakubczaplicki** [Pylons/pyramid#3206]
`Content-Encoding` as in https://tools.ietf.org/html/rfc2616#section-14.11

**Comment by tseaver** [comment]
Pyramid's `Request` class is derived from [`webob.BaseRequest`](https://docs.pylonsproject.org/projects/webob/en/stable/api/request.html), which supplies most of the heading-mapping behavior.  I think this feature belongs there.  @bertjwregeer does that seem right?

**Comment by bertjwregeer** [comment]
Content-Encoding is used by the server to let the client know what the response is encoded as. It does not apply to requests sent to the server.

https://tools.ietf.org/html/rfc7231#section-3.1.2.2

It is not used by clients, thus it is not part of the `BaseRequest` object. You may of course pull it out of `request.headers['Content-Encoding']` if you need it: https://docs.pylonsproject.org/projects/webob/en/stable/api/request.html#webob.request.BaseRequest.headers

**Comment by jakubczaplicki** [comment]
Hmm. The way I interpret https://tools.ietf.org/html/rfc7231#section-3.1.2.2 spec, is that it doesn't limit `Content-Encoding` header to be a response header only. I am probably wrong in this interpretation.

In that case when the client sends a compressed body, which header should be then set ? I struggle to find a reliable source of information.

_And yes, I understand that this question is not Pyramid-specific._

**Comment by jakubczaplicki** [comment]
Looking at how Flask handles such cases. `flask-compress` plugin is checking for 'Accept-Encoding' in the request and sets `Content-Encoding` to the response. But that's a piece of code written specifically for compressing Flask application's responses.

https://github.com/libwilliam/flask-compress/blob/master/flask_compress.py

```    def after_request(self, response):
        app = self.app or current_app
        accept_encoding = request.headers.get('Accept-Encoding', '')

        if (response.mimetype not in app.config['COMPRESS_MIMETYPES'] or
            'gzip' not in accept_encoding.lower() or
            not 200 <= response.status_code < 300 or
            (response.content_length is not None and
             response.content_length < app.config['COMPRESS_MIN_SIZE']) or
            'Content-Encoding' in response.headers):
            return response```

**Comment by bertjwregeer** [comment]
You are correct, it is not explicitly only for responses, it is a header like any other, however there is no accepted formats that a server must accept, and browsers will not ever use it. You may of course use it with a custom client.

However if it were supported by WebOb, it would need to do something sane when it encountered a `Content-Encoding: <something>` when you for example call `request.POST`. By for example on-the-fly unzipping the body.

There is no way to know whether a server accepts content that is encoded with a certain compression scheme, you may of course set the Content-Encoding header and act upon it, but because there was no good way for a server to signal what it does/does not accept there is no agreed upon header. Your best bet is to submit the content form-encoded which supports providing mime-type information.

There is a newer RFC: 
https://tools.ietf.org/html/rfc7694

That aims to improve this by allowing the server to send back an `Accept-Encoding` for an endpoint and from then on a client could send a request with `Content-Encoding`.

Adding support for `Content-Encoding` to the `BaseRequest` object is something we can definitely do, but even now it is not generally used with requests.

If you want to use `Content-Encoding` right now, today, you are on your own. WebOb can't provide you any help with `request.POST` for example, or parsing the request body with things like `request.json_body`.

`Accept-Encoding` is a header sent by the client to the server to let the server know that it can accept responses that are encoded with a particular set of encodings. WebOb can already encode the content as appropriate: https://docs.pylonsproject.org/projects/webob/en/stable/api/response.html#webob.response.Response.encode_content (https://github.com/Pylons/webob/blob/master/src/webob/response.py#L1227)

Generally encoding is done by a middleware proxy server (such as nginx/haproxy/varnish) so that it can cache the uncompressed content (given you send the appropriate HTTP headers) instead of in Python.

**Comment by mmerickel** [comment]
I think it makes sense to add `content_encoding` as a passthrough `environ_getter('HTTP_CONTENT_ENCODING')` since it is a standard header. There are certainly other headers like that and they do not imply that webob does anything special with the value.

As far as actually handling a content-encoding, this is almost always done by a proxy and would be discouraged for performance reasons to do it in python thus you would assume that the header was stripped by the proxy when it handled it.

Thus my recommendation is:

1) add the header proxy

2) don't expect webob to actually deal with the encoding in any of its methods such as `.body` or `.json_body`

**Comment by bertjwregeer** [comment]
`Content-Encoding` is not a hop-by-hop header unlike `Transfer-Encoding`, thus the WSGI application would see content that is gzip encoded if sent a request with `Content-Encoding` set.

I don't mind adding the proxy descriptor, but like `Charset` the `Content-Encoding` should affect the way WebOb handles the body, unless we decide that if `Content-Encoding` is set that it should just raise errors and say "you are on your own, here's the body_file, do with it as you please".

If a proxy uncompresses the stream sent by the client, it should appropriately update `Content-Length` and remove the `Content-Encoding` header. However, NGINX, HAProxy, varnish and others don't do this. Apache can, somewhat, if mod_deflate is configured to uncompress it, but it doesn't update Content-Length which means downstream applications can't actually read the full file size..., see https://httpd.apache.org/docs/2.4/mod/mod_deflate.html#enable and it will break your WSGI application.

**Comment by mmerickel** [comment]
If you actually think that adding a descriptor to expose the header should affect webob's processing of the body then we should just close this as won't fix. There is no scenario in which webob itself should try to handle the content-encoding header.

**Comment by jakubczaplicki** [comment]
OK. So if I understand correctly,  the only current solutions are (ordered by performance):
1. Find a robust, safe, and resistant-to-Nginx-upgrades way for Nginx to decompress the payload and pass uncompressed data to the API.
2. Explicitly require that the client must add a `Content-Encoding` ==  `gzip` header when sending compressed body. Then check the headers value as `request.headers.get('Content-Encoding') == 'gzip'`
3. Try `gzip.decompress(body)` except `pass` on every request.

**Comment by tseaver** [comment]
ISTM that if the client is *not* setting the header when sending a compressed body, the rest is moot:  neither the WSGI server nor the application can reasonably expect to do anything at all.

You could use the `config.add_request_method` [hook](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html) to add a function which did the "check and decompress" bits.

**Comment by bertjwregeer** [comment]
Luckily there is no accepted way for browsers to send compressed data, so it would have to be a custom client. The assumption then is that you are writing said custom client, and thus can make sure to set the header correctly.

Do note that `Content-Encoding` may be one of the following: `gzip, compress, deflate, br, identity`.

And, luckily no-one is insane enough to do this, but:

`Content-Encoding: gzip, br`

Means that the content was first gzipped and then brotli was applied.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

Number 2 is your best bet, and if you know it will only ever be gzip that will work fine, otherwise you will need to have a way also deal with deflate, compress, and brotli.

**Comment by bertjwregeer** [comment]
@mmerickel I do believe that if I add `request.content_encoding` then one of the next requests would be "why doesn't WebOb automatically decompress this on the fly?".

I'd be okay with a WONTFIX in this instance. There is enough support to grab the required headers manually and deal with things in an application without exposing `Content-Encoding` on the request  object which to me implied there was more support than just grabbing a header value.

**Comment by mmerickel** [comment]
> Do note that Content-Encoding may be one of the following: gzip, compress, deflate, br, identity.

`identity` is actually explicitly not allowed in a request, only in an `Accept-Encoding` response header.

If the client does not send a `Content-Encoding` request header then no one should ever try to decompress your body other than your custom server conforming to your custom protocol.

I'm closing this as WONTFIX - the header is available in `request.headers['Content-Encoding']` and can be used by any middleware that wants to detect encodings and try to handle them.
