### ISSUE TITLE
Traversal returns factory when match name is single period

### ISSUE THREAD

**Issue by di** [Pylons/pyramid#3227]
With `pyramid==1.9.1` and the following example:

```python
from waitress import serve
from pyramid.config import Configurator
from pyramid.response import Response

class Factory:
    def __init__(self, request):
        pass

    def __getitem__(self, thing):
        return thing

with Configurator() as config:
    config.add_route(
        'traverse',
        '/{thing}/',
        traverse="/{thing}",
        factory=Factory
    )
    config.add_view(
        lambda thing, request: Response(str(thing)),
        route_name='traverse'
    )
    app = config.make_wsgi_app()

serve(app, host='0.0.0.0', port=6543)
```

And the following requests:
```python
>>> import requests
>>> requests.get('http://localhost:6543/foo/').text
'foo'
>>> requests.get('http://localhost:6543/./').text
'<__main__.Factory object at 0x1088c81d0>'
```

I think I would have expected the second request to 404 because the path is equivalent to `http://localhost:6543/`, but perhaps I'm missing something here?

If this is truly a bug I'd be happy to work on it.

**Comment by bertjwregeer** [comment]
Requests doesn't do any path normalization, so this is the environ for the second request:

```
{'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'localhost:6543',
 'HTTP_USER_AGENT': 'python-requests/2.18.4',
 'PATH_INFO': '/./',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '6543',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'waitress',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'waitress.buffers.ReadOnlyFileBasedBuffer'>,
 'wsgi.input': <_io.BytesIO object at 0x106e9e570>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
```

The important bit here is the `PATH_INFO`. It is `/./` which means that your `route` matches, since all we are doing in routes is using regex comparisons. Then when the route is matched it's predicates are checked to verify that it is not disqualified, one of those predicates is [`TraversePredicate`](https://github.com/Pylons/pyramid/blob/1.9-branch/pyramid/predicates.py#L214) which calls [`traversal_path`](https://github.com/Pylons/pyramid/blob/1.9-branch/pyramid/traversal.py#L424) which eventually calls [`split_path_info`](https://github.com/Pylons/pyramid/blob/1.9-branch/pyramid/traversal.py#L526) which ignores any segments that are periods.

So traversal for:

`/whatever/./something/else/`

Would end up being:

`('whatever,'something','else')`

Since it drops any segments that are pure periods, it returns `()` which the `TraversePredicate` just sets on the `info` dictionary used by the the router, it then calls into the `ResourceTreeTraverser` which notices the tuple is empty so nothing has to be traversed, but the route still matched.

The reason you don't see a 404 is because the route matches, which matches a view, so the view is rendered.

`curl` for example already normalises the URL before sending it to the server:

```
Riley:~ xistence$ curl -vvvv "http://127.0.0.1:6543/./"
* Rebuilt URL to: http://127.0.0.1:6543/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 6543 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:6543
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Length: 153
< Content-Type: text/html; charset=UTF-8
< Date: Fri, 02 Feb 2018 22:53:25 GMT
< Server: waitress
< 
<html>
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
  The resource could not be found.<br/><br/>
/


 </body>
* Connection #0 to host 127.0.0.1 left intact
Riley:~ xistence$ curl -vvvv "http://127.0.0.1:6543/test/./"
* Rebuilt URL to: http://127.0.0.1:6543/test/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 6543 (#0)
> GET /test/ HTTP/1.1
> Host: 127.0.0.1:6543
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 4
< Content-Type: text/html; charset=UTF-8
< Date: Fri, 02 Feb 2018 22:53:34 GMT
< Server: waitress
< 
* Connection #0 to host 127.0.0.1 left intact
```

Maybe `requests` should do the same thing?

**Comment by di** [comment]
Indeed, seems like path normalization is (maybe?) on the roadmap: https://github.com/requests/requests/issues/2982

Thanks for the detailed explanation!
