### ISSUE TITLE
Incorrect documentation of pyramid.interfaces.IAuthorizationPolicy

### ISSUE THREAD

**Issue by beowulf1416** [Pylons/pyramid#3385]
The documentation for pyramid.interfaces.IAuthorizationPolicy mentions that the function permits returns either pyramid.security.Allowed or pyramid.security.Denied. The documentation for creating a custom authorization policy mentions that it should return True or False (https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#protecting-views). I tested it out and it turns out that the correct return is a True or False value.

**Comment by beowulf1416** [comment]
btw: The documentation for pyramid.interfaces.IAuthorizationPolicy is here: https://docs.pylonsproject.org/projects/pyramid/en/latest/_modules/pyramid/interfaces.html#IAuthorizationPolicy

**Comment by bertjwregeer** [comment]
You probably meant to link to this document: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#creating-your-own-authorization-policy in your first comment.

----

You can return either, but we should likely document that you want to use `Denied` and `Allowed` because it allows you add to extra information on why it was `Denied` or `Allowed`.

`pyramid.security.Denied` and `pyramid.security.Allowed` are classes that inherit from `int` and have the values `0`, and `1` respectively.

See:

https://github.com/Pylons/pyramid/blob/master/pyramid/security.py#L234-L282
