### ISSUE TITLE
PasteDeploy no longer has official repository

### ISSUE THREAD

**Issue by rbu** [Pylons/pyramid#3425]
This might be somewhat off-topic, but @ianb seems to have removed the official PasteDeploy repository from his BitBucket: https://bitbucket.org/ianb/pastedeploy/

To ensure continuity of the codebase, I would suggest you copy one of the clones to the Pylons GitHub project. Maybe @agronholm has the latest Mercurial still around? 

I found the clone at https://bitbucket.org/efren/pastedeploy/ contains the 1.5.2 tag and several changes on top which I assume were not part of the original development.

**Comment by agronholm** [comment]
I haven't done anything with PasteDeploy. I originally took over maintainership (briefly) to port it to Python 3, but I ended up never having any use for it. I don't have a local checkout anymore and the last public repo I could find was this: https://bitbucket.org/pzatrick/pastedeploy/src/default/

**Comment by rbu** [comment]
Seems @msabramo was last maintaining this, so is https://github.com/msabramo/PasteDeploy the official location?

See also https://groups.google.com/forum/#!topic/pylons-devel/PkAow1iuXXo

**Comment by rbu** [comment]
Michael, that sounds reasonable. As far as I am concerned, the file format is fine (and so is keeping PasteDeploy as indirect dependency). I just like to make sure all dependencies we use, direct or indirect, have a version control that allows us to bisect if we encounter issues.

**Comment by msabramo** [comment]
I was maintainer of PasteDeploy for a bit and no longer have time for it. I recently gave ownership of it to Chris Dent (@cdent), who requested it, because he works on OpenStack and they have a lot of dependencies on PasteDeploy.

I guess what happened and this isn't what I expected is that when I gave him ownership of the repo, it changed the URL to have his name:

https://bitbucket.org/cdent/pastedeploy

I wonder if @cdent can get Bitbucket to make https://bitbucket.org/ianb/pastedeploy a link to his repo?

**Comment by cdent** [comment]
Yeah, that wasn't what I expected either. Wherever it is _now_ my intent was to move it to github, next to https://github.com/cdent/paste and sort of start over there. I just hadn't got around to it yet because of travel last week, but should be able to do it this week if that's okay with people.

@agronholm or @mmerickel if you can give me publish access to pypi and perhaps to https://pastedeploy.readthedocs.io/ I can get it back to some form of moderate health.

In the meantime I'll see if I can get bitbucket to make a link.

**Comment by msabramo** [comment]
Nice! I'm glad to see PasteDeploy getting some love.

**Comment by agronholm** [comment]
I gave @cdent maintainer access on PyPI but as for RTD, I don't have access to that. Someone else (who I don't recognize) does: https://readthedocs.org/profiles/ilseedavid/

**Comment by cdent** [comment]
Thanks, @agronholm, I'll get something going in the next day or two, will post back here with an update when it is solid. Anybody who would like to help our, your assistance is most welcome.

**Comment by bertjwregeer** [comment]
@cdent since @mmerickel recently worked on some stuff in PasteDeploy too, would it make sense to bring it under the umbrella of the Pylons Project and give it a home in the org. With a bit of luck we can avoid the bus factor this way, and it will have a more permanent home whereby it hopefully won't move again in the future.

We've got WebOb another Ian Bicking project for example under Pylons Project as well.

**Comment by cdent** [comment]
@bertjwregeer Yeah, sure, if people are happy with that, that would be great. How should we proceed?

**Comment by mmerickel** [comment]
I think I reached out to attempt to contact the ilseedavid handle at some point and failed. Long story short is that we don't own that RTD name and I think the best solution here would be to bring PasteDeploy under the pylons project and we'll give it a url in the docs.pylonsproject.org namespace and we'll happily grant @cdent and anyone else all the access they need to work on pastedeploy.

I will make the repo right now and set it up.

@cdent we could coordinate the rest easily if drop into #pyramid on irc or we can just chat here.

**Comment by cdent** [comment]
@mmerickel I'm just finishing some stuff up that needs to be done today, but if I get that done soon, I'll join #pyramid. I'm in the UK so I may expire soon. If you don't see me today I'll try to be around most days.

**Comment by mmerickel** [comment]
I created https://github.com/Pylons/pastedeploy and invited @cdent and @msabramo. I would add @agronholm if he wants but from everything I've read they aren't interested in contributing to pastedeploy further which is fine.

I also setup https://readthedocs.org/dashboard/pylons-pastedeploy which will build its docs to https://docs.pylonsproject.org/projects/pastedeploy/en/latest/

> If you don't see me today I'll try to be around most days.

Not a problem at all. I think things are setup at least in a basic sense pretty well now and so let me know if anything is missing. I think you'll be able to turn on travis once the code is pushed, or ping me and I'll do it.

**Comment by cdent** [comment]
We might want to instead of creating the repo first, use the import tool, and import straight from https://bitbucket.org/cdent/pastedeploy/ . I did that when I was retrieving paste off bitbucket and it worked well enough.

Looking around github, as far as I can tell you can't import into an existing repo.

Doing the import smoothes over the warts of going from hg to git.

/me still doing that other thing, but this is more interesting

**Comment by mmerickel** [comment]
@cdent alright, I haven't done that before but I'll give it a shot!

**Comment by cdent** [comment]
Thanks for dealing with this. I'm still doing that other thing...

I've merged 3 of the 4 pull requests that made immediate sense. The remaining one we can do later if it makes sense, I didn't have the eyes to evaluate it effectively now (is a feature addition, the others were fixes).

Thanks again.

**Comment by mmerickel** [comment]
Take your time, just let me know when you feel it's ready to import.

**Comment by cdent** [comment]
I think the best way to keep things moving is to go ahead with the import now. Thanks.

**Comment by mmerickel** [comment]
Sounds good, it's been imported. I have no idea what to do about the issues, does anyone have experience importing bitbucket issues into a github repo?

**Comment by stevepiercy** [comment]
Sphinx did something similar when moving from https://bitbucket.org/birkenfeld/sphinx to https://github.com/sphinx-doc/sphinx. I don't know how they did it. Maybe contact the [maintainers listed on PyPI](https://pypi.org/project/Sphinx/)?

**Comment by bertjwregeer** [comment]
I am closing this issue as PasteDeploy is now safe and sound under The Pylons Project umbrella.

**Comment by stevepiercy** [comment]
Will there be any further attempt to import issues?

**Comment by mmerickel** [comment]
I think it would've needed to be done before opening other issues on the repo for it to really make sense. Regardless it's up to @cdent at this point whether he feels it should be done.

**Comment by cdent** [comment]
> Regardless it's up to @cdent at this point whether he feels it should be done.

Oh great, thanks for that responsibility.

My feeling is that most of the issues left behind on bitbucket are too old to be worried about or are relatively new ones asking for a release or related to the few patches that I merged before doing the import. Given that I think we are better off starting from scratch so that people who are having problems _now_ will show up with their _now_ problems.
