### ISSUE TITLE
Fix Python 3.8 test failure

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3471]
Fix the test failure on Python 3.8 for Pyramid 2.0:
https://travis-ci.org/Pylons/pyramid/jobs/508850032#L223

**Comment by luhn** [comment]
I took a look at this and it went a lot deeper than I was expecting.

The failing test is checking for `ConfigurationConflictError` with conflicting `@view_config`.  It checks the offending config actions by looking at `ActionInfo.src`, the value of which changes in 3.8 causing the tests to fail.  Following the trail, that value comes from `inspect.getframeinfo().code_context[0]`.  https://github.com/Pylons/venusian/blob/master/venusian/advice.py#L53

It looks like in Python 3.8 the code context for decorators has changed from the decorator itself to the decorated function, e.g. `@view_config()` becomes `def view()`.  You can see that in action here:  https://gist.github.com/luhn/d1dac5eff4d6fd0018ae12eac48e94e0  If you dig even deeper, this is happening because `sys._getframe().f_lineno` changes.

I've considered whether this is a bug in Python, but imo the code context given by 3.8 is correct.

Anyways, so as far as fixing this test, our options:

- If we consider this a bug in Python, we could file a bug report and hope it gets fixed before release.
- We could check the Python version and change the assertions based on that.  This seems bad practice.
- We could assert against something else in the `ActionInfo`, but unfortunately there doesn't seem to be anything useful there.
- We can remove the offending assertions.  This is what I would pick, because `sys._getframe()` is an implementation detail and I don't think it should be considered a stable API.  I don't think we lose much by removing them.

**Comment by bertjwregeer** [comment]
Went and looked at when the change was made, and it looks like it is related to this bug:

https://bugs.python.org/issue34876
https://github.com/python/cpython/pull/9731

The fix makes sense, and looking at the output from trace it makes sense why this change was made.

What I'd really like to see us do though is return the line number of the decorator where the issue lies so that it is easy to find the error in your source code.

Right now with stacking decorators I don't think we do the right thing in venusian to get that information, and we will just get `def view()`.

**Comment by luhn** [comment]
I don't think Venusian would be able to get that, because it's at the mercy of `sys._getframe()` within `venusian.attach`, but we should be able to get a useful frame within `pyramid.view.view_config`.  I'll see what I can do.

**Comment by bertjwregeer** [comment]
@luhn yeah, if we capture the line information in `pyramid.view.view_config` as part of the settings dictionary we can use that for reporting (and it will be more accurate even with multiple stacked decorators).

**Comment by mmerickel** [comment]
fixed by #3483
