### ISSUE TITLE
typo in remote_host

### ISSUE THREAD

**Issue by voxspox** [Pylons/pyramid#3497]
https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.remote_host

say:

**remote_host**
Gets and sets the _None_ header

I think _None_ should be something else. Maybe Host?

**Comment by bertjwregeer** [comment]
This needs to be fixed in WebOb: https://github.com/Pylons/webob/blob/master/src/webob/request.py#L316 specifically.

**Comment by luhn** [comment]
`REMOTE_HOST` corresponds with the `Host` header, correct?

**Comment by luhn** [comment]
Nope, it doesn't.

What is it?  I can't find any documentation on it.

**Comment by luhn** [comment]
Looks like [it's from the CGI spec](https://tools.ietf.org/html/rfc3875#section-4.1.9)?  (Also explains where `rfc_section` of "4.1.9" came from.)

@bertjwregeer, looks like you already fixed this with https://github.com/Pylons/webob/commit/6dbed4351a05f752b5263e8026cad8d6f22f59be

**Comment by bertjwregeer** [comment]
Yeah, it's from the CGI spec. It's basically `REMOTE_ADDR` but reverse DNS resolved (or it matches `REMOTE_ADDR`). 

I need to finish up the webob-ng (removal of Py2) branch and ship that, otherwise I may just back port that patch to fix the documentation issue. Either way, we can close this here. Thanks for your report @voxspox
