### ISSUE TITLE
modify config.scan() to default to categories=['pyramid'] instead of all categories

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#3502]
This rehashes https://github.com/Pylons/pyramid/issues/495 but I really think pyramid's `config.scan` should by default only find pyramid's decorators and if you want others you should ask for them.

I propose this as a 2.0 change, but if people want to push back we can say #495 settles it and forget about it.

**Comment by Estartu** [comment]
This change cause multiple pyramid extensions to stop working because the use different categories for the callback which IMHO is the right way. So you can if you need to filter some callbacks. 

The simplest solution for extension developers to fix this issue is to change the category of there callbacks to 'pyramid' removing the possibility to filter.

I see no benefit in this change and a lot of drawbacks.
