### ISSUE TITLE
docs: a table of scaffold names

### ISSUE THREAD

**Issue by mikeorr** [Pylons/pyramid#402]
I made this ReST table of scaffold names in Pyramid 1.3 vs 1.2. It may be useful in the Pyramid manual. It was originally for the Akhet manual but I'm not sure if I'll use it there..

    =================    ==========  ====================    ======================
    Routing mechanism    Database    Pyramid 1.3 scaffold    Pyramid 1.2.4 scaffold
    =================    ==========  ====================    ======================
    URL dispatch         SQLAlchemy  **alchemy**             routesalchemy
    URL dispatch         \-          **starter**             \-
    Traversal            ZODB        **zodb**                zodb
    Traversal            SQLAlchemy  \-                      alchemy
    Traversal            \-          \-                      starter
    =================    ==========  ====================    ======================

**Comment by stevepiercy** [comment]
I'm going to close this issue because it is covered in the latest version of the docs. Feel free to reopen.

* http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/project.html?highlight=scaffold#scaffolds-included-with-pyramid
* http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/scaffolds.html?highlight=scaffold#steps
* http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tour.html?highlight=scaffold # the pyramid_jinja2 add-on provides a new scaffold pyramid_jinja2_starter
